const assert = require('assert');
const Core = require('../app/core.js');
let s = Core.createInitialState(10000, 100);
s = Core.updateQuote(s, 'GOOGL', 100, 98);
s = Core.applyOrder(s, { symbol: 'GOOGL', side: 'BUY', quantity: 10, note: 'test' }, '2026-01-01T00:00:00Z');
assert.strictEqual(s.cash, 9000);
assert.strictEqual(s.positions.GOOGL.shares, 10);
assert.strictEqual(s.positions.GOOGL.averageCost, 100);
assert.throws(() => Core.applyOrder(s, { symbol: 'GOOGL', side: 'BUY', quantity: 1000 }), /Insufficient/);
assert.throws(() => Core.applyOrder(s, { symbol: 'GOOGL', side: 'SELL', quantity: 11 }), /Cannot sell/);
s = Core.updateQuote(s, 'GOOGL', 120, 100);
assert.strictEqual(Core.unrealizedPL(s), 200);
s = Core.applyOrder(s, { symbol: 'GOOGL', side: 'SELL', quantity: 4 }, '2026-01-02T00:00:00Z');
assert.strictEqual(s.cash, 9480);
assert.strictEqual(s.positions.GOOGL.shares, 6);
assert.strictEqual(s.positions.GOOGL.averageCost, 100);
assert.strictEqual(s.realizedPL, 80);
assert.strictEqual(Core.unrealizedPL(s), 120);
s = Core.applyOrder(s, { symbol: 'GOOGL', side: 'SELL', quantity: 6 }, '2026-01-03T00:00:00Z');
assert.strictEqual(s.positions.GOOGL.shares, 0);
assert.strictEqual(s.positions.GOOGL.averageCost, 0);
assert.strictEqual(s.realizedPL, 200);
assert.throws(() => Core.validateOrder(s, { symbol: 'GOOGL', side: 'BUY', quantity: 0 }), /greater than zero/);
assert.throws(() => Core.validateOrder(s, { symbol: 'GOOGL', side: 'BUY', quantity: 0.000001 }), /at least \$0\.01/);
s = Core.addJournalEntry(s, { symbol: 'GOOG', stance: 'WATCH', thesis: 'Observe AI/cloud momentum', confidence: 75 });
assert.strictEqual(s.journal.length, 1);
const a = Core.analytics(s);
assert.strictEqual(a.trades, 3);
assert.ok(Core.benchmark(s).buyHoldValue > 0);
console.log('accounting tests passed');
